name: GitHub Pages

on:
  push:
    branches:
      - trunk

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: '0.4.7'

      - run: |
          mdbook build
          rm book/{ayu-highlight.css,tomorrow-night.css}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
          commit_message: Publish book
